package com.example.utils

object Localization {
    enum class Language {
        EN, BN, HI
    }

    private val translations = mapOf(
        Language.EN to mapOf(
            "app_name" to "EasyBook",
            "login" to "LOGIN",
            "register" to "REGISTER",
            "shop_name" to "SHOP NAME",
            "owner_name" to "OWNER NAME",
            "email" to "EMAIL ADDRESS",
            "whatsapp" to "WHATSAPP NUMBER",
            "password" to "PASSWORD",
            "old_password" to "OLD PASSWORD",
            "new_password" to "NEW PASSWORD",
            "forgot_password" to "Forgot Password?",
            "dashboard" to "DASHBOARD",
            "total_remaining" to "Total Remaining",
            "search_placeholder" to "Search name, mobile or Unique ID...",
            "settings" to "SETTINGS",
            "logout" to "Logout",
            "delete_account" to "Delete Account",
            "add_customer" to "ADD CUSTOMER",
            "customer_name" to "CUSTOMER NAME",
            "mobile_number" to "MOBILE NUMBER",
            "save" to "SAVE",
            "cancel" to "CANCEL",
            "confirm" to "CONFIRM",
            "add_entry" to "Add Ledger Entry",
            "record_debt" to "GIVE CREDIT (DEBT)",
            "record_deposit" to "RECEIVE PAYMENT (DEPOSIT)",
            "total_customers" to "Total Customers",
            "sound_vibration" to "Sound & Vibration",
            "sound" to "Sound Effects",
            "vibration" to "Haptic Vibration",
            "language" to "App Language",
            "currency" to "Currency Style",
            "date_range" to "Filter: Date to Date",
            "start_date" to "From Date",
            "end_date" to "To Date",
            "all_entries" to "All Ledger Entries",
            "pay_off" to "Settle Balance",
            "unique_id" to "Unique ID",
            "delete_customer" to "Delete Customer",
            "no_customers" to "No customers added yet.",
            "no_transactions" to "No transactions logged.",
            "forgot_pwd_dialog" to "A reset password link has been sent to your email. Please check your Inbox and Spam folders on your Gmail app.",
            "spam_alert" to "Check Spam Folder!",
            "enter_amount" to "Enter Amount",
            "notes" to "Remarks/Notes",
            "amount_required" to "Please enter a valid amount.",
            "customer_added" to "Customer registered successfully!",
            "customer_deleted" to "Customer permanently deleted.",
            "transaction_added" to "Entry added successfully!",
            "transaction_deleted" to "Entry deleted.",
            "error_fields" to "Please fill all required fields correctly.",
            "confirm_delete_owner" to "Are you sure you want to delete your merchant account? This will erase all ledger records. Enter password to confirm:",
            "confirm_delete_customer" to "Are you sure you want to delete this customer? This will erase all ledger entries for this customer. Enter merchant password to confirm:",
            "remaining" to "Owed",
            "deposited" to "Deposited"
        ),
        Language.BN to mapOf(
            "app_name" to "EasyBook",
            "login" to "লগইন",
            "register" to "রেজিস্টার",
            "shop_name" to "দোকানের নাম",
            "owner_name" to "মালিকের নাম",
            "email" to "ইমেল ঠিকানা",
            "whatsapp" to "হোয়াটসঅ্যাপ নম্বর",
            "password" to "পাসওয়ার্ড",
            "old_password" to "পুরানো পাসওয়ার্ড",
            "new_password" to "নতুন পাসওয়ার্ড",
            "forgot_password" to "পাসওয়ার্ড ভুলে গেছেন?",
            "dashboard" to "ড্যাশবোর্ড",
            "total_remaining" to "মোট বাকি টাকা",
            "search_placeholder" to "নাম, মোবাইল বা ইউনিক আইডি দিয়ে খুঁজুন...",
            "settings" to "সেটিংস",
            "logout" to "লগআউট",
            "delete_account" to "অ্যাকাউন্ট মুছুন",
            "add_customer" to "গ্রাহক যোগ করুন",
            "customer_name" to "গ্রাহকের নাম",
            "mobile_number" to "মোবাইল নম্বর",
            "save" to "সংরক্ষণ করুন",
            "cancel" to "বাতিল",
            "confirm" to "নিশ্চিত করুন",
            "add_entry" to "হিসাব লিখুন",
            "record_debt" to "ধার দিন (DEBT)",
            "record_deposit" to "টাকা জমা নিন (DEPOSIT)",
            "total_customers" to "মোট গ্রাহক সংখ্যা",
            "sound_vibration" to "শব্দ এবং ভাইব্রেশন",
            "sound" to "শব্দ প্রভাব",
            "vibration" to "ভাইব্রেশন",
            "language" to "অ্যাপের ভাষা",
            "currency" to "মুদ্রার ধরন",
            "date_range" to "তারিখ অনুযায়ী ফিল্টার",
            "start_date" to "শুরুর তারিখ",
            "end_date" to "শেষের তারিখ",
            "all_entries" to "সমস্ত হিসাবের তালিকা",
            "pay_off" to "হিসাব চুকিয়ে দিন",
            "unique_id" to "ইউনিক আইডি",
            "delete_customer" to "গ্রাহক মুছুন",
            "no_customers" to "কোনো গ্রাহক পাওয়া যায়নি।",
            "no_transactions" to "কোনো হিসাবের এন্ট্রি নেই।",
            "forgot_pwd_dialog" to "আপনার ইমেলে পাসওয়ার্ড রিসেট লিঙ্ক পাঠানো হয়েছে। দয়া করে আপনার জিমেইল অ্যাপের স্প্যাম ফোল্ডার চেক করুন।",
            "spam_alert" to "স্প্যাম ফোল্ডার দেখুন!",
            "enter_amount" to "টাকার পরিমাণ লিখুন",
            "notes" to "মন্তব্য/নোট",
            "amount_required" to "দয়া করে সঠিক পরিমাণ লিখুন।",
            "customer_added" to "গ্রাহক সফলভাবে যোগ করা হয়েছে!",
            "customer_deleted" to "গ্রাহক চিরতরে মুছে ফেলা হয়েছে।",
            "transaction_added" to "হিসাব সফলভাবে যোগ করা হয়েছে!",
            "transaction_deleted" to "হিসাব মুছে ফেলা হয়েছে।",
            "error_fields" to "দয়া করে সমস্ত তথ্য সঠিকভাবে পূরণ করুন।",
            "confirm_delete_owner" to "আপনি কি নিশ্চিত যে আপনি আপনার অ্যাকাউন্টটি মুছে ফেলতে চান? এটি সমস্ত রেকর্ড মুছে ফেলবে। নিশ্চিত করতে পাসওয়ার্ড লিখুন:",
            "confirm_delete_customer" to "আপনি কি নিশ্চিত যে আপনি এই গ্রাহককে মুছে ফেলতে চান? এটি গ্রাহকের সমস্ত হিসাব মুছে ফেলবে। নিশ্চিত করতে মালিকের পাসওয়ার্ড লিখুন:",
            "remaining" to "বাকি",
            "deposited" to "জমা"
        ),
        Language.HI to mapOf(
            "app_name" to "EasyBook",
            "login" to "लॉगिन",
            "register" to "रजिस्टर",
            "shop_name" to "दुकान का नाम",
            "owner_name" to "मालिक का नाम",
            "email" to "ईमेल पता",
            "whatsapp" to "व्हाट्सएप नंबर",
            "password" to "पासवर्ड",
            "old_password" to "पुराना पासवर्ड",
            "new_password" to "नया पासवर्ड",
            "forgot_password" to "पासवर्ड भूल गए?",
            "dashboard" to "डैशबोर्ड",
            "total_remaining" to "कुल शेष राशि",
            "search_placeholder" to "नाम, मोबाइल या यूनिक आईडी से खोजें...",
            "settings" to "सेटिंग्स",
            "logout" to "लॉगआउट",
            "delete_account" to "खाता हटाएं",
            "add_customer" to "ग्राहक जोड़ें",
            "customer_name" to "ग्राहक का नाम",
            "mobile_number" to "मोबाइल नंबर",
            "save" to "सुरक्षित करें",
            "cancel" to "रद्द करें",
            "confirm" to "पुष्टि करें",
            "add_entry" to "लेनदेन दर्ज करें",
            "record_debt" to "उधार दें (DEBT)",
            "record_deposit" to "भुगतान लें (DEPOSIT)",
            "total_customers" to "कुल ग्राहक संख्या",
            "sound_vibration" to "ध्वनि और कंपन",
            "sound" to "ध्वनि प्रभाव",
            "vibration" to "वाइब्रेशन",
            "language" to "ऐप की भाषा",
            "currency" to "मुद्रा प्रारूप",
            "date_range" to "दिनांक से दिनांक फ़िल्टर",
            "start_date" to "प्रारंभ तिथि",
            "end_date" to "अंतिम तिथि",
            "all_entries" to "सभी लेनदेन का इतिहास",
            "pay_off" to "पूर्ण भुगतान करें",
            "unique_id" to "यूनिक आईडी",
            "delete_customer" to "ग्राहक हटाएं",
            "no_customers" to "कोई ग्राहक नहीं मिला।",
            "no_transactions" to "कोई लेनदेन दर्ज नहीं है।",
            "forgot_pwd_dialog" to "पासवर्ड रीसेट लिंक आपके ईमेल पर भेज दिया गया है। कृपया अपने जीमेल ऐप के स्पैम फ़ोल्डर की जांच करें।",
            "spam_alert" to "स्पैम फ़ोल्डर देखें!",
            "enter_amount" to "राशि दर्ज करें",
            "notes" to "टिप्पणी/विवरण",
            "amount_required" to "कृपया सही राशि दर्ज करें।",
            "customer_added" to "ग्राहक सफलतापूर्वक जोड़ा गया!",
            "customer_deleted" to "ग्राहक स्थायी रूप से हटा दिया गया।",
            "transaction_added" to "लेनदेन सफलतापूर्वक जोड़ा गया!",
            "transaction_deleted" to "लेनदेन हटाया गया।",
            "error_fields" to "कृपया सभी आवश्यक जानकारी सही ढंग से भरें।",
            "confirm_delete_owner" to "क्या आप वाकई अपना मर्चेंट खाता हटाना चाहते हैं? इससे सभी लेनदेन रिकॉर्ड नष्ट हो जाएंगे। पुष्टि के लिए पासवर्ड दर्ज करें:",
            "confirm_delete_customer" to "क्या आप वाकई इस ग्राहक को हटाना चाहते हैं? इससे इस ग्राहक के सभी लेनदेन इतिहास नष्ट हो जाएंगे। पुष्टि के लिए पासवर्ड दर्ज करें:",
            "remaining" to "उधार",
            "deposited" to "जमा"
        )
    )

    fun getString(key: String, langCode: String): String {
        val lang = try {
            Language.valueOf(langCode.uppercase())
        } catch (e: Exception) {
            Language.EN
        }
        return translations[lang]?.get(key) ?: translations[Language.EN]?.get(key) ?: key
    }
}
